import NavbarDesktop from "@/components/layout/navbar/NavbarDesktop";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
         {/* Navbar */}
      <NavbarDesktop />
        {children}
      </body>
    </html>
  );
}
